name: Process Weekly Emails
on:
  workflow_dispatch:
jobs:
  Process-Weekly-Emails:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
      DO_SPACES_NAME: ${{ secrets.DO_SPACES_NAME }}
      DO_SPACES_ENDPOINT: ${{ secrets.DO_SPACES_ENDPOINT }}
      DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
      DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Slack Notification - Start
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Starting weekly 311 report notifications pipeline..."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Process notifications
        run: cd scripts/weekly-emails && sh run-weekly-emails.sh
        shell: bash
      - name: Slack Notification - Finish
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "weekly 311 report notifications Pipeline Finished | Job Status: ${{ job.status }}"
